[project]
name = "imdb-backup-lists"
version = "0.1.0"
description = "A simple tool to backup all your lists from IMDb"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pyinstaller>=6.11.1",
    "requests>=2.32.3",
    "unidecode>=1.3.8",
]
